### ISSUE TITLE
Tag Lambdas

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/template-kaskadi-api#11]
On AWS we can tag lambdas (`tag:appName:foobar`) we should do that here per API as well (keep the name simple!)

**Comment by alexlemaire** [comment]
Added tags (see [here](https://github.com/kaskadi/template-kaskadi-api/pull/10#discussion_r391513393)).

I also implemented them for `template-kaskadi-lambda`

**Comment by alexlemaire** [comment]
Closing for now.
