### ISSUE TITLE
Add user prompting to add-lambda

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/template-kaskadi-api#19]
**Is your feature request related to a problem? Please describe.**
Using the `add-lambda` tool via `npm run add-lambda name method path` feels bad

**Describe the solution you'd like**
Would be better if we could just run `npm run add-lambda` and it would prompt for name, method and path.

See [here](https://github.com/kaskadi/template-kaskadi-api/blob/master/tools/add-lambda/add-lambda.js) for `add-lambda` tool source code.

This requires to replace the [following block](https://github.com/kaskadi/template-kaskadi-api/blob/69f6c5277c25d7f77e49b269d518c23fcffd90ee/tools/add-lambda/add-lambda.js#L9-L15) by [this line](https://github.com/kaskadi/template-kaskadi-api/blob/69f6c5277c25d7f77e49b269d518c23fcffd90ee/tools/add-lambda/add-lambda.js#L15) (no parameters for the function needed most likely).

We then can rewrite `getArgs` to be a `getData` which simply prompts user for a `name`, `method` and `path` and returns an object containing those 3 fields (so we keep backward compatibility for the rest of the code)

**Illustration:**
```js
/**
 * @function getData
 * @returns {object} - should contain the lambda name, method and path
 */
module.exports = () => {
  // TODO: prompt user for name, method and path
  return { name, method, path }
}
```

Once done, we can get rid of `checkArgs` helper all along.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by beatadetkova** [comment]
test

**Comment by alexlemaire** [comment]
Implemented, closing now!
