### ISSUE TITLE
Reinforce data validation

### ISSUE THREAD

**Issue by alexlemaire** [kaskadi/template-kaskadi-api#21]
**Is your feature request related to a problem? Please describe.**
With the current data validation, users can input an invalid method as well as some funky paths/names. Would be nice to add some solid validation here.

**Describe the solution you'd like**
Validation I'd like to see:
- **method**: should only accept valid HTTP methods. Check the list of HTTP methods existing and then validate the user input against that. **Careful:** method should also be lower cased because that's what serverless is expecting. If the method is inputted as uppercase it'll create an error!
- **path/name**: those two should only contain lower cased characters and no spaces/special characters. Only `-` is a valid separator in `path` and `name` (no `get_apps` path or name for example, this makes it harder for user to read)

**Comment by beatadetkova** [comment]
I can take care of it!
