### ISSUE TITLE
serverless http methods

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/template-kaskadi-api#9]
are http methods in serverless really supposed to be lowercase or is it a feature that serverless is forgiving in that regard? 

... as per http spec methods must be uppercase...

**Comment by alexlemaire** [comment]
Never tried in uppercase honestly. I've just followed the documentation which has it lowercase so I don't know if it's robust enough to take in uppercase (I'd expect it to do `method = method.upperCase()` in the background but cannot tell for sure)
